pipeline {
   agent any   
   
     
    stages {
        stage('Build') {
            steps {
                def mvnHome = "/bin/mvn"  // Replace this with the actual path to Maven executable
            sh "${mvnHome}/bin/mvn -B -DskipTests clean package"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {              
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
