pipeline {
   agent any   
   
     
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean test'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {              
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
